# Generated by Django 4.2.1 on 2023-12-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['id'], 'verbose_name': 'Дочернее меню', 'verbose_name_plural': 'Дочернее меню'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание основного меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название основного меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание дочернего меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название дочернего меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='При клике на пункт меню кидает на сайт', max_length=200, verbose_name='Ссылка на другой сайт'),
        ),
    ]
